### Listing table preparation

In [1]:
import pandas as pd
import numpy as np

Open 'listing' table

In [2]:
df = pd.read_csv('./listings.csv')

C:\Users\MrShaddy\AppData\Local\Temp\ipykernel_12340\3056600813.py:1: DtypeWarning: Columns (61,62,94,95) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('./listings.csv')

Select columns what we will need for analyze

In [3]:
result_listing = df[['id', 'listing_url', 'host_id', 'neighbourhood', 'latitude', 'longitude', 'bathrooms', 'bedrooms', 'beds', 'bed_type', 'square_feet',
                     'price', 'weekly_price', 'monthly_price', 'security_deposit', 'cleaning_fee', 'minimum_nights', 'maximum_nights',
                     'availability_365', 'review_scores_rating']]
result_listing

,id,listing_url,host_id,neighbourhood,latitude,longitude,bathrooms,bedrooms,beds,bed_type,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,minimum_nights,maximum_nights,availability_365,review_scores_rating
0,11551,https://www.airbnb.com/rooms/11551,43039,Brixton,51.46225,-0.11732,1.0,1.0,1.0,Real Bed,NaN,$88.00,$645.00,"$2,350.00",$400.00,$30.00,3,180,336,92.0
1,38151,https://www.airbnb.com/rooms/38151,163634,LB of Croydon,51.41940,-0.08722,NaN,1.0,NaN,Real Bed,NaN,$65.00,NaN,NaN,NaN,NaN,1,730,365,NaN
2,13913,https://www.airbnb.com/rooms/13913,54730,LB of Islington,51.56802,-0.11121,1.0,1.0,0.0,Real Bed,538.0,$65.00,$333.00,"$1,176.00",$100.00,$15.00,1,29,365,97.0
3,38407,https://www.airbnb.com/rooms/38407,164566,LB of Tower Hamlets,51.49995,-0.02624,1.0,1.0,1.0,Real Bed,NaN,$79.00,$530.00,"$2,100.00",NaN,NaN,2,365,5,95.0
4,90700,https://www.airbnb.com/rooms/90700,491286,Notting Hill,51.51074,-0.19853,1.0,1.0,1.0,Real Bed,NaN,$105.00,NaN,NaN,$0.00,$35.00,2,1125,268,88.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85063,39868875,https://www.airbnb.com/rooms/39868875,13553423,LB of Waltham Forest,51.58208,-0.00915,1.0,1.0,1.0,Real Bed,NaN,$70.00,NaN,NaN,$200.00,$30.00,3,30,88,NaN
85064,39869123,https://www.airbnb.com/rooms/39869123,21145791,LB of Merton,51.40628,-0.23244,1.0,1.0,2.0,Real Bed,NaN,$69.00,NaN,NaN,$200.00,$25.00,2,1125,113,NaN
85065,39869214,https://www.airbnb.com/rooms/39869214,251922260,LB of Hammersmith & Fulham,51.50244,-0.21547,1.0,1.0,2.0,Real Bed,NaN,$90.00,NaN,NaN,NaN,$55.00,3,1125,63,NaN
85066,39869249,https://www.airbnb.com/rooms/39869249,255372486,LB of Bromley,51.35742,0.10764,1.5,1.0,1.0,Real Bed,NaN,$30.00,NaN,NaN,$100.00,$10.00,2,1125,1,NaN
85067,39869282,https://www.airbnb.com/rooms/39869282,210531062,City of Westminster,51.51090,-0.12480,1.5,1.0,1.0,Real Bed,NaN,$187.00,NaN,NaN,$0.00,$30.00,1,90,311,NaN

We can see some NaN values in prices. we will fill it as 0.0 for future calculations

In [4]:
result_listing = result_listing.fillna(0.0)

For calculations we need to convert our prices to 'float'.

In [5]:
def price_to_float(price):
    if type(price) == str:
        price = price.replace('$', '')
        price = price.replace(',', '')
        return float(price)
    else:
        return price

result_listing['price'] = result_listing['price'].map(price_to_float)
result_listing['weekly_price'] = result_listing['weekly_price'].map(price_to_float)
result_listing['monthly_price'] = result_listing['monthly_price'].map(price_to_float)
result_listing['security_deposit'] = result_listing['security_deposit'].map(price_to_float)
result_listing['cleaning_fee'] = result_listing['cleaning_fee'].map(price_to_float)

We will mean what if object has 0 in weekly and monthly prices, it has no discount for long time rent. So, we will calculate it with this way:
night price * 7 as weekly price and
night price * 31 as monthly price

In [6]:
result_listing['weekly_price'] = (result_listing['price'] * 7).where(result_listing['weekly_price'] == 0, result_listing['weekly_price'])
result_listing['monthly_price'] = (result_listing['price'] * 31).where(result_listing['monthly_price'] == 0, result_listing['monthly_price'])
result_listing

,id,listing_url,host_id,neighbourhood,latitude,longitude,bathrooms,bedrooms,beds,bed_type,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,minimum_nights,maximum_nights,availability_365,review_scores_rating
0,11551,https://www.airbnb.com/rooms/11551,43039,Brixton,51.46225,-0.11732,1.0,1.0,1.0,Real Bed,0.0,88.0,645.0,2350.0,400.0,30.0,3,180,336,92.0
1,38151,https://www.airbnb.com/rooms/38151,163634,LB of Croydon,51.41940,-0.08722,0.0,1.0,0.0,Real Bed,0.0,65.0,455.0,2015.0,0.0,0.0,1,730,365,0.0
2,13913,https://www.airbnb.com/rooms/13913,54730,LB of Islington,51.56802,-0.11121,1.0,1.0,0.0,Real Bed,538.0,65.0,333.0,1176.0,100.0,15.0,1,29,365,97.0
3,38407,https://www.airbnb.com/rooms/38407,164566,LB of Tower Hamlets,51.49995,-0.02624,1.0,1.0,1.0,Real Bed,0.0,79.0,530.0,2100.0,0.0,0.0,2,365,5,95.0
4,90700,https://www.airbnb.com/rooms/90700,491286,Notting Hill,51.51074,-0.19853,1.0,1.0,1.0,Real Bed,0.0,105.0,735.0,3255.0,0.0,35.0,2,1125,268,88.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85063,39868875,https://www.airbnb.com/rooms/39868875,13553423,LB of Waltham Forest,51.58208,-0.00915,1.0,1.0,1.0,Real Bed,0.0,70.0,490.0,2170.0,200.0,30.0,3,30,88,0.0
85064,39869123,https://www.airbnb.com/rooms/39869123,21145791,LB of Merton,51.40628,-0.23244,1.0,1.0,2.0,Real Bed,0.0,69.0,483.0,2139.0,200.0,25.0,2,1125,113,0.0
85065,39869214,https://www.airbnb.com/rooms/39869214,251922260,LB of Hammersmith & Fulham,51.50244,-0.21547,1.0,1.0,2.0,Real Bed,0.0,90.0,630.0,2790.0,0.0,55.0,3,1125,63,0.0
85066,39869249,https://www.airbnb.com/rooms/39869249,255372486,LB of Bromley,51.35742,0.10764,1.5,1.0,1.0,Real Bed,0.0,30.0,210.0,930.0,100.0,10.0,2,1125,1,0.0
85067,39869282,https://www.airbnb.com/rooms/39869282,210531062,City of Westminster,51.51090,-0.12480,1.5,1.0,1.0,Real Bed,0.0,187.0,1309.0,5797.0,0.0,30.0,1,90,311,0.0

Save result to our prapared table

In [7]:
result_listing.to_csv('./result_listing.csv', index=False)